[package]
name = "server"
version = "0.1.0"
authors = [ "Gary Ascuy <gary.ascuy@gmail.com>" ]
edition = "2018"
publish = false

[dependencies]
rocket = "0.4.4"
cargo-watch = "7.3.0"

[profile.dev]
panic = "abort"
